#it should take the configMap data of DB_HOST: mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql   #this is the Service name of mysql service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: app
    project: expense
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      #name: backend
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: mohansai7/backend:v1
        resources:
          requests:  #min things, required requests, this requests should be less than or equal to/the limits
            cpu: 100m
            memory: 128Mi
          limits:  #this is the max limit, and limits should be equal or greater than the requests
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: backend  #name should be same as above replicas metadata
  namespace: expense
spec:
  selector:
    project: expense
    app: backend
    tier: app
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: 8080
    targetPort: 8080


---
# creating HPA ---> HorizontalPodAutoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15 #usually in real time projects, this target cpu utilization or threshold is 75%





