
#below will create mysql replica of 2 worker nodes:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: mohansai7/mysql:v1

---

#below will create service that transfers the requests to Pods in the worker node:
#To connect to this mysql(any other application or pod if wants to connect to mysql, here backend needs to connect to mysql), service to be created as below.

apiVersion: v1
kind: Service
metadata:
  name: mysql #name should be same, also in backend, it is provided DB_HOST: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3306
    targetPort: 3306  #both port(service port) and target port(container ports) should be 3306
    